# Generated by Django 4.2.3 on 2023-07-08 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fechaVenta', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('costoTotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipoPerfil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('capacida_vehiculo', models.IntegerField()),
                ('documentacion', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=500)),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=100)),
                ('nombre2', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('contrasenia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('id_producto_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.productocategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.agricultor')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Mayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.usuario'),
        ),
        migrations.CreateModel(
            name='CarritoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.carrito')),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cod_metodoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.metodopago'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='idMayorita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.mayorista'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bodega', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='agricultor',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCAH.usuario'),
        ),
    ]
